FROM bitnami/node:8-prod

ENV TERM=xterm
ENV ROOT /var/www/kubeless-ui
ENV NODE_ENV=production

RUN mkdir -p $ROOT/dist && \
    mkdir -p $ROOT/src
COPY package.json $ROOT/src/

WORKDIR $ROOT/src

RUN install_packages apt-transport-https gnupg && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get purge -y gnupg && \
    apt-get clean
RUN install_packages yarn

EXPOSE 3000

# build & test
COPY . $ROOT/src/
RUN yarn cache clean && npm cache clean --force && rm -rf /tmp/*
