version: '2'
services:
  dev:
    image: joaonart/kubeless-ui-dev
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: bash -c "yarn install && npm rebuild node-sass && yarn run dev"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
