version: '2'

services:
  prod:
    image: joaonart/kubeless-ui-prod
    # build:
    #   context: .
    #   dockerfile: Dockerfile-prod
    command: bash -c "yarn install && npm rebuild node-sass && yarn run build && yarn run start"
    environment:
      NODE_ENV: production
      PORT: 3000
    volumes:
      - .:/var/www/kubeless-ui/src
      - /var/www/kubeless-ui/src/node_modules
    ports:
      - "3000:3000"
